### ISSUE TITLE
Gibberish output

### ISSUE THREAD

**Issue by godspirit00** [shivammehta007/Neural-HMM#17]
Hello,
I'm training a model on a dataset of ~5 hrs , ~2800 samples.
Now it's at 22k steps, and using `synthesis.ipynb` the model generates some gibberish output.

https://user-images.githubusercontent.com/16176151/179481529-dd20d7bf-e2e4-420d-84dc-3247797acd8d.mp4

The text is `The Secret Service believed that it was very doubtful that any President would ride regularly in a vehicle with a fixed top, even though transparent.`

The training says `Variance Floored` many times during the process.
And in tensorboard, some charts look strange with some `NaN`s on it.
For example:
![20220718172543](https://user-images.githubusercontent.com/16176151/179482815-6b1f17aa-ba5e-40f4-9fdf-f33539f9a489.jpg)

What am I missing? 
Thanks!

**Comment by shivammehta007** [comment]
Just to confirm are you training it in English or any other language? If it is any other language ensure that the phonetisation and the symbols dictionary match in `text/symbols.py`. 

If it is in English and you are using the default phonetisation then could you please share the images of the tensorboard? What do the forward alignments look like, and how is the mel-synthesised by the mean of the most probable state, and also the synthesised mel also what was the batch size during the training?

**Comment by shivammehta007** [comment]
I don't see anything unusual in the images, but the data seems to have numerous pauses which could be challenging for the model to learn if you are training from scratch with a somewhat limited amount of data (please note it also depends on how you are annotating the pauses if they are not annotated it might also add on to the challenge of learning the alignments from scratch).

An effective method in such a scenario is to fine-tune the pretrained LJSpeech model with the data that you have ([similar to this article](https://2022.fonetik.se/contributions/Lameris%20et%20al.%20-%202022%20-%20Spontaneous%20neural%20HMM%20TTS%20with%20prosodic%20feature%20m.pdf)), just change the filelists in `src/hparams.py` and load the pretrained LJSPeech checkpoint before you begin training with `python train.py -c <Neural-HMM.ckpy>`.
