### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by Zaverichintanoxolo** [shivammehta007/Neural-HMM#3]
I am able to build the docker environment successfully but when I try to run 
`python train.py `
I get following error: 
`Segmentation fault (core dumped)`

**Comment by Zaverichintanoxolo** [comment]
Had to build from custom docker image - now it works

**Comment by shivammehta007** [comment]
Which image did you use? That will be useful for everyone else as well.

**Comment by Zaverichintanoxolo** [comment]
Instead of starting with PyTorch docker image, I started with 
`FROM ubuntu:20.04`
